 ## tasks file for /home/daji/artifactory/roles/artifactory
---
# Variable setup.

- name: Include OS-Specific variables
  include_vars: "{{ ansible_os_family }}.yml"


# Setup/install tasks.

- include_tasks: setup-Ubuntu.yml
  when: ansible_os_family == 'Ubuntu'