---

- name: 'create user to run artifactory'
  user:
    name: "{{ artifactory_username }}"
    password: "{{ artifactory_password }}"
    home: /opt/artifactory/
    shell: /bin/bash
    system: true
  tags:
    - users
  

- name: Add the Apt key
  apt_key:
    url: "{{ artifactory_repo_key_url }}"
    state: present

- name: 'verify presence of artifactory repo'
  apt_repository:
    repo: "{{ artifactory_repo_url }}"
    state: present
    update_cache: true



- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes

- name: Install artifactory ce
  apt:
  # name: jfrog-artifactory-cpp-ce
    name: jfrog-artifactory-{{ artifactory_version }}
    state: present

- name: Start service if not started
  service:
    name: artifactory
    state: started

  #- name: 'download artifactory'
  #unarchive:
  #  copy: no
  #  src: "{{ artifactory_url }}"
  #  dest: /opt/artifactory/
  #  validate_certs: no
  #retries: 3
  #when: not artifactory_jarfile.stat.exists


#- name: 'apt install prerequisites'
#  apt:
#    name: openssl
#    state: present
#    update_cache: yes
#  retries: 3
#  register: result
#  until: result is succeeded


