---

#- name: 'create user to run artifactory'
#  user:
#    name: "{{ artifactory_username }}"
#    password: "{{ artifactory_password }}"
#    home: /opt/artifactory/
#    shell: /bin/bash
#    system: true
#  tags:
#    - users

- name: create group for artifactory
  group:
    name: "{{ artifactory_group }}"
    state: present

- name: create user for artifactory
  user:
    name: "{{ artifactory_user }}"
    group: "{{ artifactory_group }}"
    system: yes

- name: ensure artifactory_download_directory exists
  file:
    path: "{{ artifactory_download_directory }}"
    state: directory

- name: download artifactory
  unarchive:
    src: "{{ artifactory_zip }}"
    dest: "{{ artifactory_download_directory }}"
    remote_src: yes
    owner: "{{ artifactory_user }}"
    group: "{{ artifactory_group }}"
   # creates: "{{ artifactory_home }}"
  register: downloadartifactory
  until: downloadartifactory is succeeded
  retries: 3
  notify:
    - restart artifactory

- name: ensure artifactory_file_store_dir exists
  file:
    path: "{{ artifactory_file_store_dir }}"
    state: directory


#- name: create artifactory service
#  import_role:
#    name: robertdebock.service

#- name: start and enable artifactory
#  service:
#    name: artifactory
#    state: started
#    enabled: yes

- name: execute shell script to start it
  shell: "{{ artifactory_exec }}"
